### ISSUE TITLE
Windows: file operations don't always succeed as expected

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#114]
Issues:
- shutil.rmtree or os.remove does not always ensure that files are fully removed after function returns
- remove may take multiple attempts to succeed
- mkdir(path, exist_ok=True) might have a race condition if it is called just after the folder is "removed"

I noticed that sometimes in `travis_build_script.py`, try_remove_tree() didn't always remove the file immediately (the file would exist for some time after the function was called. The function used to be defined like this:

```python
def try_remove_tree(path):
	try:
		if os.path.isdir(path):
			shutil.rmtree(path)
		else:
			os.remove(path)
	except FileNotFoundError:
		pass
```

but I changed it to this

```python
def try_remove_tree(path):
	try:
		if os.path.isdir(path):
			shutil.rmtree(path)
		else:
			os.remove(path)
	except FileNotFoundError:
		pass

	# Make sure the folder is really removed
	poll_cnt = 0
	while os.path.exists(path):
		print(f"Waiting for {path} to be removed ({poll_cnt})")
		if poll_cnt < 5:
			time.sleep(1)
		else:
			raise Exception(f"Folder {path} could not be removed!")

		poll_cnt += 1
```

The `# Make sure the folder is really removed` did trigger on my machine (at least once), and after 1 second the file was "properly" removed.

If this behavior can happen on windows, we should also update the installer scripts, which use the same functions, to add this kind of functionality.

The installer scripts currently don't do multiple attempts when doing operations like extraction, deletion etc, so it may be worth checking for those sort of issues as well.

**Comment by drojf** [comment]
Someone reported getting "Access is denied" messages when installing Onikakushi. Some excerpts from the log below. It appears the installer failed to remove the CG and CGAlt folders, then 7zip failed to overwrite those files.

```
----- Details -----
Permission error: See our installer wiki FAQ about this error at https://07th-mod.com/wiki/Higurashi/Higurashi-Part-1---Voice-and-Graphics-Patch/#extraction-stage-fails-i-get-an-acess-denied-error-when-overwriting-files

 Could not extract [Onikakushi Ch.1 Downloads\Onikakushi-Graphics.7z]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\threading.py", line 926, in _bootstrap_inner
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\threading.py", line 870, in run
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\httpGUI.py", line 562, in errorPrintingInstaller
    installerFunction(args)
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 283, in main
    installer.extractFiles()
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 145, in extractFiles
    self.downloaderAndExtractor.extract()
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\common.py", line 907, in extract
    destinationFileName)
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\common.py", line 634, in extractOrCopyFile
    raise SevenZipException("{}\n\n Could not extract [{}]".format(monitor.getErrorMessage(), sourcePath))
common.SevenZipException: Permission error: See our installer wiki FAQ about this error at https://07th-mod.com/wiki/Higurashi/Higurashi-Part-1---Voice-and-Graphics-Patch/#extraction-stage-fails-i-get-an-acess-denied-error-when-overwriting-files

 Could not extract [Onikakushi Ch.1 Downloads\Onikakushi-Graphics.7z]
```

```
VersionManager: Not saving local version info as this is the 'first' install
Full Update Detected: Deleting old CG and CGAlt folders
WARNING: Failed to clean up the [D:\SteamLibrary\steamapps\common\Higurashi When They Cry\HigurashiEp01_Data\StreamingAssets\CG] directory
Traceback (most recent call last):
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\shutil.py", line 398, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'D:\\SteamLibrary\\steamapps\\common\\Higurashi When They Cry\\HigurashiEp01_Data\\StreamingAssets\\CG\\07thlogo.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 127, in cleanOld
    forceRmTree(oldCG)
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 35, in forceRmTree
    shutil.rmtree(path, onerror=on_rm_error)
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\shutil.py", line 400, in _rmtree_unsafe
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 22, in on_rm_error
    os.unlink(path)
PermissionError: [WinError 5] Access is denied: 'D:\\SteamLibrary\\steamapps\\common\\Higurashi When They Cry\\HigurashiEp01_Data\\StreamingAssets\\CG\\07thlogo.png'
WARNING: Failed to clean up the [D:\SteamLibrary\steamapps\common\Higurashi When They Cry\HigurashiEp01_Data\StreamingAssets\CGAlt] directory
Traceback (most recent call last):
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\shutil.py", line 398, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'D:\\SteamLibrary\\steamapps\\common\\Higurashi When They Cry\\HigurashiEp01_Data\\StreamingAssets\\CGAlt\\me_mi_aw_a1.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 134, in cleanOld
    forceRmTree(oldCGAlt)
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 35, in forceRmTree
    shutil.rmtree(path, onerror=on_rm_error)
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\shutil.py", line 400, in _rmtree_unsafe
  File "C:\Users\USERNAME_OMITTED\Downloads\07th-mod_installer\higurashiInstaller.py", line 22, in on_rm_error
    os.unlink(path)
PermissionError: [WinError 5] Access is denied: 'D:\\SteamLibrary\\steamapps\\common\\Higurashi When They Cry\\HigurashiEp01_Data\\StreamingAssets\\CGAlt\\me_mi_aw_a1.png'
Extracting...
<<< Status: 45% Extracting [Onikakushi-Graphics.7z (715.22 MB)] to [D:\SteamLibrary\steamapps\common\Higurashi When They Cry]  >>>
----- BEGIN EXECUTING COMMAND: [./7za64 x Onikakushi Ch.1 Downloads\Onikakushi-Graphics.7z -aoa -bso1 -bsp1 -bse2 -oD:\SteamLibrary\steamapps\common\Higurashi When They Cry] -----

```

7zip gives lots of errors like

```
150 . HigurashiEp01_Data\StreamingAssets\CG\ex_tips.png
ERROR: Can not delete output file : Access is denied. : D:\SteamLibrary\steamapps\common\Higurashi When They Cry\HigurashiEp01_Data\StreamingAssets\CG\haikei.png
```

I asked the user to move the install folder to somewhere else (in case they were not allowed to write to the normal folder), but it didn't seem to help.

Besides the above "try  multiple times", it may be worth halting the install at that point, and asking the user to manually delete the folder (if a "delete folder" operation failed)

I also told the user to try the items in this FAQ: https://07th-mod.com/wiki/Installer/faq/#extraction-stage-fails-i-get-an-acess-denied-error-when-overwriting-files

Log attached below (I anonymized their username)
[MOD-INSTALLER-LOG-2020-08-15_20-13-32.zip](https://github.com/07th-mod/python-patcher/files/5079846/MOD-INSTALLER-LOG-2020-08-15_20-13-32.zip)

**Comment by drojf** [comment]
Rather than fixing this issue properly, if it only happens to a small subset of users, I propose the following:

- Add an option to the installer to "install" to a dummy folder (rather than the game folder)
- Tell the user to overwrite the game files with this dummy folder manually

This was actually how tellow wrote the higurashi installer previously on all OSs - it would extract all files to a temp folder, then move them to the final destination (automatically, though). We now only do this on linux and macos, not on windows, which I changed in e80431fa44a675b10f4a4b5a2ce5615b13dc4a21 (although I don't remember why I changed it)

This would also help solve some of the other issues we have where installs don't work correctly, as the installer then acts more as a "manual install helper" which aids you in downloading the correct files.

This might introduce some issues if the installer scripts do anything funky, but it should work for the most part (after all, it would be the same as a manual install)

Another option (which I had already wanted to add anyway) would be to have a "download only" option, and let users manually extract each file.

**Comment by ooa113y** [comment]
> (although I don't remember why I changed it)

From what I remember, this was to make cross-disk installs faster by avoiding moving files to what might be a different device, since cross-device moves are significantly slower -- I actually have no idea why this change is applied *only* on Windows, though. Other OSes would benefit from it just as much.

**Comment by drojf** [comment]
I think I remembered why - on Windows, even if it's on the same disk, moving would take ages as Windows Defender would attempt to scan every individual file, and for Higurashi you have so many voice/lipsync files. Although, I'm not sure if that's 100% true still, would need to re-test the behavior.

That was why it was Windows only, but you're right that if it's across disks, it would need to re-copy everything, so other OS's would benefit in that case.
