### ISSUE TITLE
Make Higurashi console arc install requirements more clear

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#33]
As the console arcs install over higurashi ep4, if the user already has a modded ep4 the install will fail as the installer stops once it realizes where are already some mod files in the folder.

We should make it more clear what the requirements are to install the console arcs. Could someone fill me in on how this should work?

**Comment by ItaloKnox** [comment]
I'm not sure why the installer should fail if the user already has a modded version of EP4, though I do understand if the purpose is to not break his existing game.

The ideal scenario would be like this:

1. installer checks if the EP4 folder is modded (nowadays you can just check the tips.json if you want a fast check)
2. if it's modded, it would warn the user about it
    * instead of failing the installation, it is better to just ask if they want to make a copy of it or overwrite the current patch
         * let they choose a location for the new copy if they decide to do it
3. Clean up the folders ``Update``, ``CompiledUpdateScripts``, ``CG``, ``CGAlt``, ``voice``, ``spectrum`` and install the patch

Now, if the installer finds an unmodded copy of the patch:

1. Ask the user if they want to make a copy of the folder to not break EP4
2. If they decide to make a copy, let them choose where to install it
3. install the patch

Having an unmodded game should not be a requirement, but instead a recommendation.

**Comment by drojf** [comment]
I think I was wrong about why the install fails - from the error log it looks like it fails at the 'cleaing up' stage. I investigated it and can't see anything we can do to stop this error from happeneing - we'll just have to print "couldnt' delete folder".

```
07th Mod - Install failed due to error: [WinError 145] The directory is not empty: 'C:/Users/USERNAME/Downloads/Games/PC Sources/Higurashi/Higurashi no Naku koro Ni Sui - Console Arcs/Higurashi04Himatsubushi\\HigurashiEp04_Data\\StreamingAssets\\CG\\scenario'
Exception in thread Thread-86:
Traceback (most recent call last):
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\httpGUI.py", line 375, in errorPrintingInstaller
    installerFunction(args)
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\higurashiInstaller.py", line 182, in main
    installer.cleanOld()
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\higurashiInstaller.py", line 85, in cleanOld
    shutil.rmtree(oldCG)
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\python\lib\shutil.py", line 507, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\python\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\python\lib\shutil.py", line 395, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\USERNAME\Downloads\07th-Mod.Installer.win64\higu_win_installer\install_data\python\lib\shutil.py", line 393, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:/Users/USERNAME/Downloads/Games/PC Sources/Higurashi/Higurashi no Naku koro Ni Sui - Console Arcs/Higurashi04Himatsubushi\\HigurashiEp04_Data\\StreamingAssets\\CG\\scenario'
```

For now i'll fix this bug and add an error message. Later I'll try to fix it 'properly' with your instructions
