### ISSUE TITLE
Special Characters in hostname causes installer to crash (on Windows only?)

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#63]
A user had the following error:

```
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    installerGUI.server_test()
  File "E:\Steam\steamapps\higu_win_installer_32\install_data\httpGUI.py", line 643, in server_test
    serverStartedCallback=on_server_started)
  File "E:\Steam\steamapps\higu_win_installer_32\install_data\httpGUI.py", line 279, in start_server
    httpd = HTTPServerNoReuse(("127.0.0.1", 0), CustomHandler)
  File "E:\Steam\steamapps\higu_win_installer_32\install_data\python\lib\socketserver.py", line 449, in __init__
    self.server_bind()
  File "E:\Steam\steamapps\higu_win_installer_32\install_data\python\lib\http\server.py", line 139, in server_bind
    self.server_name = socket.getfqdn(host)
  File "E:\Steam\steamapps\higu_win_installer_32\install_data\python\lib\socket.py", line 676, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 9: invalid start byte
```

This is related to these python bugs: 
- https://bugs.python.org/issue9377
- https://bugs.python.org/issue26227 
- https://bugs.python.org/issue26226#msg259077

The offending character was: П

We could add a check if the computer hostname contains non-ascii characters (on windows only), and tell the user to change it before starting the install. I don't think we can fix this otherwise if it's a bug in the python library itself.

Or check if updated python versions don't have this error (I think the issue still hasn't been fully fixed even on newer python versions anyway).

I tried just running socket.gethostbyaddr([BADNAME]), but I think the gethostbyaddr referred to inside socket is a different call altogeher (the python bug issues comments state is is the raw windows call), so i don't think you can use that to test - you must set your actual computer hostname and run the code.

Interestingly I get this warning if I try to set such a name, and windows doesn't let me set it:
![image](https://user-images.githubusercontent.com/1249449/58625391-bf630400-8315-11e9-9f2c-5c49572dedc9.png)

**Comment by drojf** [comment]
As per the above commit, I added a check for if this happens, so I'm closing this issue. This is just a check, not a fix - the user still has to change their hostname to plain ASCII.
