### ISSUE TITLE
Exception in v0.0.58

### ISSUE THREAD

**Issue by enumag** [07th-mod/python-patcher#69]
Trying to install Meakashi patch using the latest release:

```
Exception handling [gamePaths] request: Traceback (most recent call last):
  File "C:\Users\Enumag\Downloads\07th-mod_installer\httpGUI.py", line 664, in handleInstallerData
    responseDataJson = requestHandler(requestData)
  File "C:\Users\Enumag\Downloads\07th-mod_installer\httpGUI.py", line 480, in getGamePathsHandler
    fullInstallConfigs = gameScanner.scanForFullInstallConfigs(selectedSubMods)
  File "C:\Users\Enumag\Downloads\07th-mod_installer\gameScanner.py", line 471, in scanForFullInstallConfigs
    possibleIdentifiers = getPossibleIdentifiersFromPath(gamePath)
  File "C:\Users\Enumag\Downloads\07th-mod_installer\gameScanner.py", line 420, in getPossibleIdentifiersFromPath
    return os.listdir(path)
NotADirectoryError: [WinError 267] The directory name is invalid: 'c:\\program files (x86)\\steam\\steamapps\\common\\Higurashi saves.lnk'
```

**Comment by enumag** [comment]
I have a link file in the `C:\Program Files (x86)\Steam\steamapps\common` directory for easier access to Higurashi saves. Looks like the installer fails to ignore links properly.

**Comment by drojf** [comment]
it's worse than that - it would raise an exception if ANY file (as in, not a directory) was in the steam common folder :S
