### ISSUE TITLE
getaddrinfo failure on startup

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#75]
A user reported a getaddinfo failure on startup, causing the installer to crash. User had malwarebytes installed (does this even provide a firewall), and uninstalling it/rebooting the computer didn't seem to help.

The user could access the 07th-mod website just fine, which suggests it's some software blocking only our installer from running, and not an external firewall/connection issue. Otherwise, it's something to do with the python/networking configuration, or us incorrectly configuring/using the library, resulting in it failing only on certain people's computers.

```
> Install Started On 2019-09-18 21:07:07.883761
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)]
Installer Build Information: Build Date: 2019-08-21 13:35:51.907653
Git Tag (Version): v0.0.76

Installer is being run from: [C:\Users\USER\Desktop\07th-mod_installer]
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    check07thModServerConnection()
  File "main.py", line 68, in check07thModServerConnection
    testFile = urlopen(Request("http://07th-mod.com/", headers={"User-Agent": ""}))
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\USER\Desktop\07th-mod_installer\python\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

**Comment by drojf** [comment]
User could run the installer fine on a different computer, so it must be something to do with that computer's setup and not something external.

This may be a valid option to add to the FAQ, as you can easily use one computer to mod the game, then copy the game to the other computer to play it.

**Comment by drojf** [comment]
The installer now has a 'loading' screen which works even if no internet connection is available, so any sort of network error on startup won't crash and instead will display an error message on the installer web-ui (the current error message will tell the user to check their internet connection, and also direct them to the FAQ).

This combined with the updated FAQ is about the best I can do to solve this issue, so I'm closing this issue.
