### ISSUE TITLE
Unicode in JSON breaks installers running on Python 2.6 (Mac users) 

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#89]
See https://github.com/07th-mod/python-patcher/commit/c235f3a818c83df944788ebeb508530badd1dc71

```
User selected options for install:
Option ID: [BGM Options: Restore system0] Value: [False]
Exception Thrown handling request startInstall: 'ascii' codec can't encode character u'\u2606' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/USERNAME/Downloads/07th-Mod.Installer.mac/install_data/httpGUI.py", line 727, in handleInstallerData
    responseDataJson = requestHandler(requestData)
  File "/Users/USERNAME/Downloads/07th-Mod.Installer.mac/install_data/httpGUI.py", line 560, in startInstallHandler
    logger.printNoTerminal(modOption)
  File "/Users/USERNAME/Downloads/07th-Mod.Installer.mac/install_data/logger.py", line 156, in printNoTerminal
    "{}\n".format(message),
  File "/Users/USERNAME/Downloads/07th-Mod.Installer.mac/install_data/installConfiguration.py", line 125, in __repr__
    return "Option ID: [{}] Value: [{}]".format(self.id, self.value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2606' in position 23: ordinal not in range(128)
```

**Comment by drojf** [comment]
Fixed in e7143f49cc7d32a9bb0c12a791358541728ffec9
